Task/3 lecture 1 subtask 1 button
js-tasks-ru/htmlcss-20210708_kirill-lappo pull request #3
Opened 2021-07-15 08:18 UTC by Kira-Lappo

* added button styles for active, disabled, hovered states. Added primary, secondary and alternative states.
* added button examples 
* added normalize.css package
* added .editorconfig

2021-07-15 16:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-15 16:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-15 16:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-15 16:16 UTC, GSemikozov requested changes

2021-07-15 16:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
font-weight + line-height лучше указать сразу + padding

2021-07-15 16:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
для disabled элементов рекомендуется добавлять pointer-events: none чтобы пользователь не мог нажать

2021-07-15 16:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
если элемент disabled и у него pointer-events: none, то ховер определять не нужно

2021-07-15 16:16 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_type_primary {
лучше без слова `_type` =)

2021-07-15 16:52 UTC, Kira-Lappo commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
блин, в голове мелькнуло, но не вспомнил про это

2021-07-15 16:54 UTC, Kira-Lappo commented on 03-lection1/01-button/button.css
> +.button_type_primary {
я думал по БЭМу типа имя-проперти_значение-проперти

2021-07-15 17:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-15 17:15 UTC, Kira-Lappo commented on 03-lection1/01-button/button.css
> +.button_type_primary {
убрал type_ из имен

2021-07-15 17:16 UTC, Kira-Lappo commented on 03-lection1/01-button/button.css
> +    opacity: 0.5;
добавил

2021-07-15 17:16 UTC, Kira-Lappo commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
добавил

2021-07-15 17:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-16 08:27 UTC, GSemikozov approved these changes

2021-07-16 08:27 UTC, merged