Task/4 lecture 1 subtask 1 accordion
js-tasks-ru/htmlcss-20210708_kirill-lappo pull request #6
Opened 2021-07-17 18:37 UTC by Kira-Lappo

* added accordion styles
    * added background and  details color
* added accordion examples

2021-07-17 18:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-17 19:28 UTC, GSemikozov requested changes

2021-07-17 19:28 UTC, GSemikozov commented on assets/css/main.css
> +    --details: #495057;
сильно размытое определение / имя - "детали"... надо бы как-то конкретизировать. Плюс - не уверен что этот цвет специфичен именно для аккордиона

2021-07-17 20:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-17 20:50 UTC, Kira-Lappo commented on assets/css/main.css
> +    --details: #495057;
не специфичен, поэтому я и назвал размыто details, технически он мб использован как подпись к тем же картинкам

2021-07-18 09:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 10:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 10:09 UTC, Kira-Lappo commented on assets/css/main.css
> +    --details: #495057;
переименовал в `--accordion-details-foreground` мб получше будет

2021-07-18 10:38 UTC, GSemikozov commented on assets/css/main.css
> +    --details: #495057;
да, так читается однозначно лучше

2021-07-18 10:38 UTC, GSemikozov approved these changes

2021-07-18 10:38 UTC, merged